### ISSUE TITLE
Can`t repeat after finish dugeon

### ISSUE THREAD

**Issue by Yuug3nD** [Samsterr/sir-squirrel-assistant#19]
![Screenshot (13)](https://github.com/user-attachments/assets/a69b7063-e780-442a-aca3-eb31dca7de1c)
[squirrel.log](https://github.com/user-attachments/files/17351791/squirrel.log)
Hello Samster, 
Can you please check this problem. Just when finish the dugeon, it didnt repeat.
p/s: no bonus weekly btw

**Comment by Samsterr** [comment]
This seems to be an issue seems to be related to your squad_order.json file. can you copy the contents of the file to this website https://jsonlint.com/ to check if its valid. Also can i check is it stuck on the part where the battle pass shows up?

**Comment by Yuug3nD** [comment]
> This issue seems to be related to your squad_order.json file. can you copy the contents of the file to this website https://jsonlint.com/ to check if its valid. Also can i check is it stuck on the part where the battle pass shows up?

it said valid. It stucked when claimed the reward

**Comment by Samsterr** [comment]
Ok can i check if you have this in your squad_order.json
![{6C2CA1E2-4462-4C82-B0A3-71975B071B0A}](https://github.com/user-attachments/assets/db91febe-1244-4309-a620-c54583f59809)

also can you help me test this hotfix to see if it fixes your issue
[sirsquirrel_hotfix.zip](https://github.com/user-attachments/files/17352647/sirsquirrel_hotfix.zip)

**Comment by Yuug3nD** [comment]
[squad_order.json](https://github.com/user-attachments/files/17352659/squad_order.json)
here is my squad_order.json
i read your note, so i change the default to test

**Comment by Samsterr** [comment]
i have tested your squad_order and there doesn't seem to be an issue. As for the freezing on reward claiming can i confirm if its 1 or 2 that you are stuck on
1) 
![{289C3204-017A-4AE3-A8D4-E45D647F44BF}](https://github.com/user-attachments/assets/1ad5bad1-af11-4b9c-88b1-5d431a5d3264)
2)
![{FA36F440-B894-4D51-BFEE-DDBECF47452C}](https://github.com/user-attachments/assets/7d93a526-4992-467f-b64a-c9e70c670980)

**Comment by Yuug3nD** [comment]
It’s number 1

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Samsterr ***@***.***>
Đã gửi: Sunday, October 13, 2024 8:42:07 AM
Đến: Samsterr/sir-squirrel-assistant ***@***.***>
Cc: Phạm Tấn Phát ***@***.***>; Author ***@***.***>
Chủ đề: Re: [Samsterr/sir-squirrel-assistant] Can`t repeat after finish dugeon (Issue #19)


i have tested your squad_order and there doesn't seem to be an issue. As for the freezing on reward claiming can i confirm if its 1 or 2 that you are stuck on
1)
289C3204-017A-4AE3-A8D4-E45D647F44BF.png (view on web)<https://github.com/user-attachments/assets/1ad5bad1-af11-4b9c-88b1-5d431a5d3264>
2)
FA36F440-B894-4D51-BFEE-DDBECF47452C.png (view on web)<https://github.com/user-attachments/assets/7d93a526-4992-467f-b64a-c9e70c670980>

**Comment by Yuug3nD** [comment]
After i click claim then battle pass  lvl count, when i need click confrim. Its stuck right there

**Comment by Samsterr** [comment]
@Yuug3nD please try this and see if it solves your issue
[sirsquirrel hotfix.zip](https://github.com/user-attachments/files/17352786/sirsquirrel.hotfix.zip)

**Comment by Yuug3nD** [comment]
Okay i will. After few run i will reply you back.

**Comment by Yuug3nD** [comment]
[squirrel.log](https://github.com/user-attachments/files/17353226/squirrel.log)
![image](https://github.com/user-attachments/assets/4f5c13d6-0aa8-4afc-9ab7-0cd0107f6382)
The third run, it cant pick the sinners

**Comment by Samsterr** [comment]
@Yuug3nD Thanks for the screenshot. The issue seems to be related to the confirm button not being the same size as compared to when you have extra cost and starlight  bonuses which i did not take into account. This hotfix should fix your issue and lemme know if you still have any issues
[sirsquirrel.zip](https://github.com/user-attachments/files/17353273/sirsquirrel.zip)

**Comment by Yuug3nD** [comment]
i need to set default team in squad_order.json right ?

**Comment by Samsterr** [comment]
> i need to set default team in squad_order.json right ?

yes

**Comment by Yuug3nD** [comment]
> > i need to set default team in squad_order.json right ?
> 
> yes

it`s work, thanks you 👍

**Comment by Yuug3nD** [comment]
but now another problem ✌️ i will open another

**Comment by Samsterr** [comment]
@Yuug3nD i have made an error on this, please grab the latest hotfix for the proper fix thanks

**Comment by Yuug3nD** [comment]
Ok thanks
