### ISSUE TITLE
Can`t pass through this event

### ISSUE THREAD

**Issue by Yuug3nD** [Samsterr/sir-squirrel-assistant#20]
![Screenshot (15)](https://github.com/user-attachments/assets/2bb38c90-6f19-4fc1-97d3-b42bbd886598)
When ever i go to this event. It will stuck.

**Comment by Yuug3nD** [comment]
![image](https://github.com/user-attachments/assets/08bbcd00-5fd0-4284-aa51-3ea816ca155f)
I think here is the log

**Comment by Samsterr** [comment]
@Yuug3nD thanks for letting me know that this event still isnt handled properly. i actually just managed to get this event in MD so it should be fixed now. Do let me know if the hotfix breaks other "Select To Gain EGO gifts"
[sirsquirrel KQE hotfix.zip](https://github.com/user-attachments/files/17355512/sirsquirrel.KQE.hotfix.zip)

**Comment by Yuug3nD** [comment]
> @Yuug3nD thanks for letting me know that this event still isnt handled properly. i actually just managed to get this event in MD so it should be fixed now. Do let me know if the hotfix breaks other "Select To Gain EGO gifts" [sirsquirrel KQE hotfix.zip](https://github.com/user-attachments/files/17355512/sirsquirrel.KQE.hotfix.zip)

yeah i got another one ✌️ it`s boss event 
![image](https://github.com/user-attachments/assets/70410dbe-c6ab-4bbf-8123-611c2ceb1096)
![image](https://github.com/user-attachments/assets/3c22684a-65dc-4df0-a880-f2b11080877f)

**Comment by Yuug3nD** [comment]
[squirrel.log](https://github.com/user-attachments/files/17356124/squirrel.log)

**Comment by Samsterr** [comment]
This seems like an issue with the library pyautogui which i am using for mouse movements. For now just rerun the bot as this seems to be a rare issue that i probably can fix by swapping which library im using.

**Comment by Samsterr** [comment]
@Yuug3nD i have fixed the issue and you can grab the hotfix from the latest release.
