### ISSUE TITLE
Do You Wanna Get Beat Boss Loop

### ISSUE THREAD

**Issue by AnemicGoblin** [Samsterr/sir-squirrel-assistant#24]
Whenever it got Do You Wanna Get Beat? Hurtily? boss, in the choice event part, it doesn't do anything other than spam clicking the left mouse, even if you guide the mouse to finish the event, the mouse still spam clicks without moving. There's no error on the log.

**Comment by Samsterr** [comment]
@AnemicGoblin can i check if you are using the hotfix i put out for 0.8.5

**Comment by AnemicGoblin** [comment]
I tried using the hotfix, but the mouse didn't click the continue button and just looping between skip button and ego symbol

![image](https://github.com/user-attachments/assets/a97f8432-cb45-4921-8501-5daa1373901b)

**Comment by Samsterr** [comment]
Can i have your squirrel.log output

**Comment by AnemicGoblin** [comment]
![image](https://github.com/user-attachments/assets/fbfb52e9-d426-439b-93b4-eb9029f92c76)

**Comment by Samsterr** [comment]
Can i have the output around the time you encountered the factory boss.

**Comment by AnemicGoblin** [comment]
The fight happens at 09:27-09:30 ish, there"s no other output on the log at that time.

**Comment by Samsterr** [comment]
can i check how did you run the bot. because this output indicate you never even did a battle

**Comment by AnemicGoblin** [comment]
I run it using cmd as per the instructions

![image](https://github.com/user-attachments/assets/41b7ee5a-3524-4ce6-bdbc-ac13b37dfa94)

**Comment by AnemicGoblin** [comment]
![image](https://github.com/user-attachments/assets/a5726bfe-a5f6-4b48-8ace-a08997d84042)
Heres another of that same boss encounter at 06:38, there's no log at that time too

**Comment by Samsterr** [comment]
[sirsquirrel.zip](https://github.com/user-attachments/files/17448327/sirsquirrel.zip)
can you try this exe instead to see if it fixes your issue

**Comment by AnemicGoblin** [comment]
Ill try it and get back to you when I encounter DYWGBH boss again, thank you.

**Comment by Samsterr** [comment]
hang on i uploaded the wrong one use this instead
[sirsquirrel.zip](https://github.com/user-attachments/files/17448566/sirsquirrel.zip)

**Comment by AnemicGoblin** [comment]
I tried using the new one but few problems shows up before I managed to reach the boss, first, after I got any ego gifts from regular node, the file crash (the top one), and when in a pack selection, it also crashes (the bottom one, but strangely enough it only happens sometimes. ill show the pack selection screen too).

![image](https://github.com/user-attachments/assets/4c69571a-78cb-40ad-b067-26ea202c3f1d)

![image](https://github.com/user-attachments/assets/e2de0925-5be2-40ce-bcc2-468de1bfba00)

**Comment by Samsterr** [comment]
@AnemicGoblin sorry can you provide the log and i forgot that due to a dependency picture i added it will crash without it.
can you try the 0.9 prerelease ver here https://github.com/Samsterr/sir-squirrel-assistant/releases/tag/0.9.0

**Comment by Samsterr** [comment]
@AnemicGoblin Closing because issue has now been settled in the latest 0.9.0 hotfix
