### ISSUE TITLE
Can you make it so we can select which ego gifts we get to pick at the start?

### ISSUE THREAD

**Issue by SongOfTheFates** [Samsterr/sir-squirrel-assistant#32]
If it's possible I'd like to get some use out of my Shi Association identities, and they would really benefit from the script picking the 3rd slash ego gift that enormously buffs them. Priority on upgrading certain gifts, if possible, would be excellent too.

Otherwise, the script is running perfectly. Thanks again for the time you've put into this!

**Comment by Samsterr** [comment]
@SongOfTheFates i dont have any feedback about slash gifts cause i dont really use it but just left it there incase someone wanted to so i can make that change for you. As for choosing which gifts to upgrade while it is possible, do understand if that were so i would need to get images of every single gift which isnt really practical right now as how upgrading works is by detecting the gift type followed by the keywordless gifts. I will consider it adding this if i can find a more appropriate way of doing it

**Comment by SongOfTheFates** [comment]
Makes sense, thanks again!
