### ISSUE TITLE
Random ego gifts didn't show

### ISSUE THREAD

**Issue by tomkhoailang** [Samsterr/sir-squirrel-assistant#33]
After entering stimulation, the cursor do point to the Random card which is showing below but the gift options didn't change in the right side, result in selecting two blank sections

![image](https://github.com/user-attachments/assets/f4827483-7383-40f1-864f-f30c99478cfe)
[squirrel.log](https://github.com/user-attachments/files/17531440/squirrel.log)

**Comment by Samsterr** [comment]
@tomkhoailang issue should be fixed in the latest hotfix
