### ISSUE TITLE
Running at a lower resolution

### ISSUE THREAD

**Issue by hamazakm** [Samsterr/sir-squirrel-assistant#35]
Any way to run at a monitor with lower resolution than 1920x1080p?
Thanks

**Comment by Samsterr** [comment]
@hamazakm i'm currently testing more resolution aware code for the detection as it is currently working off the 1080p UI. I will let you know again once i have done enough testing for it

**Comment by hamazakm** [comment]
I see thanks for your reply

**Comment by Samsterr** [comment]
@hamazakm i have released the first test version of the resolution aware version if you would like to help test it.
link: https://github.com/Samsterr/sir-squirrel-assistant/releases/tag/0.9.2

**Comment by Samsterr** [comment]
closing issue, moved to general feedback here #37
