### ISSUE TITLE
Sir Squirrel starts, then doesn't do anything.

### ISSUE THREAD

**Issue by Loomshade** [Samsterr/sir-squirrel-assistant#36]
Followed the entirety of the README instructions, and made sure to check if my Antivirus was snubbing it, but alas, no luck.

Every time I attempt to run the program as explained, generated within the log is
> 2024-10-31 19:03:59,410 - __main__ - INFO - Run 1
> 2024-10-31 19:03:59,641 - src.core - INFO - Converting Enkephalin to Modules
> 2024-10-31 19:04:00,124 - src.core - INFO - Navigating to Mirror Dungeon
> 2024-10-31 19:04:00,495 - __main__ - INFO - Current Team: poise
or some variation, of course based on the time and config.

All the configs have been double checked, and when the command is put in to run the app, the command window simply stalls until I choose to close it. My laptop has a funky Over-2K resolution, but as instructed, I set the game to Windowed mode at 1080P and put it in the top-left corner of the screen. Since everything seems to be right, I can only assume there's an issue with the application itself, hence bringing up this issue.

It seems to me like the app thinks that it's running successfully, but nothing is happening, and so when it hits a point where it's looking for confirmation that it's on a certain screen, it never gets it and infinitely stalls. And since there's no video or related I could find of the app actually running, I have no idea what's actually supposed to happen.

Here's hoping this is a simple fix or something I somehow simply overlooked. Either way, cheers for making this Auto-MD, it's something I've been needing for months and months.

**Comment by Samsterr** [comment]
@Loomshade I am aware of issues relating to sir squirrel running on non 16:9 resolutions. i am currently working on a resolution aware version which requires some testing, if you want to help i have linked it in this comment. simply copy over the config and pictures folder from the main release and to where you extracted the res aware version and run it as usual. if not a fix would be to set your laptop window to a 16:9 resolution which is 2560x1440 for 2k and 1920x1080 for hd and then run limbus accordingly.

Link to the res aware version: https://github.com/Samsterr/sir-squirrel-assistant/releases/tag/0.9.2

**Comment by Samsterr** [comment]
closing, same issue as #37
