### ISSUE TITLE
First launch not working

### ISSUE THREAD

**Issue by lukatin9** [Samsterr/sir-squirrel-assistant#47]
![obraz](https://github.com/user-attachments/assets/27a69f11-7fc8-4176-b771-b7d8fd67258d)

Just installed it, didn't change anything and thats what shows up

**Comment by Samsterr** [comment]
@lukatin9 for my releases you need the latest 7z as well as the hotfix. Grab the 1.0.1 7z and then copy the hotfix exe over after extracting
